spring:
  application:
   name: zfx-mp
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/mp? useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL =false
   username: root
   password: root
 
##########--------------------mp的sql日志打印 --------------------##########
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 开启自动驼峰命名规则（camel case）映射
  mapper-locations: classpath*:mapper/*.xml # 给mapper XML文件定义一个和mapper接口不同的存放路径
  type-aliases-package: com.zfx.mp.entity #设置MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
##  config-location: classpath:mybatis‐config.xml  #定义mybatis-config.xml配置路径